# Generated by Django 5.2.10 on 2026-02-03 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_create_date_contact_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('created_date',)},
        ),
    ]
